### ISSUE TITLE
смысл "времени цикла"?

### ISSUE THREAD

**Issue by newdarkstar** [koval01/my_code#3]
для чего это вообще? скрипт тупо ждет указанное время **после** выполнения всех атак. с какой целью?
я бы понимал, если бы ты каждые n секунд запускал **один** цикл атаки, то тогда все бы работало как ты задумал.

**Comment by koval01** [comment]
Цикл здесь испульзуеться для проверки статуса атаки, с заданным интервалом отправляется запрос на локальный веб-сервер и если прогресс дошел до конца, то программа закрывается. Поэтому если вы указываете большое количество циклов, то лучше выбирать большую задержку.
